/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mywallet;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertEquals(1, 1);
    }
}
